//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shmuelie.MSBuild.Compression {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shmuelie.MSBuild.Compression.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving directory &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string ArchiveDirectory_Comment {
            get {
                return ResourceManager.GetString("ArchiveDirectory.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3941: Failed to archive directory &quot;{0}&quot; because it does not exist or is inaccessible..
        /// </summary>
        internal static string ArchiveDirectory_ErrorDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ArchiveDirectory.ErrorDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3943: Failed to archive directory &quot;{0}&quot; to file &quot;{1}&quot;.  {2}.
        /// </summary>
        internal static string ArchiveDirectory_ErrorFailed {
            get {
                return ResourceManager.GetString("ArchiveDirectory.ErrorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3942: Failed to create archive file &quot;{0}&quot; because it already exists.  Please delete or rename the file and try again..
        /// </summary>
        internal static string ArchiveDirectory_ErrorFileExists {
            get {
                return ResourceManager.GetString("ArchiveDirectory.ErrorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format {0} does not support {1} compression..
        /// </summary>
        internal static string ArchiveDirectory_InvalidArchiveCompression {
            get {
                return ResourceManager.GetString("ArchiveDirectory.InvalidArchiveCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not extract from file &quot;{0}&quot; to file &quot;{1}&quot; because the &quot;{2}&quot; parameter was set to &quot;{3}&quot; in the project and the files&apos; sizes and timestamps match..
        /// </summary>
        internal static string Extract_DidNotExtractBecauseOfFileMatch {
            get {
                return ResourceManager.GetString("Extract.DidNotExtractBecauseOfFileMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not extract file &quot;{0}&quot; because it didn&apos;t match the include filter or because it matched the exclude filter..
        /// </summary>
        internal static string Extract_DidNotExtractBecauseOfFilter {
            get {
                return ResourceManager.GetString("Extract.DidNotExtractBecauseOfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3931: Failed to extract to directory &quot;{0}&quot; because it could not be created.  {1}.
        /// </summary>
        internal static string Extract_ErrorCouldNotCreateDestinationDirectory {
            get {
                return ResourceManager.GetString("Extract.ErrorCouldNotCreateDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3936: Failed to open extract file &quot;{0}&quot; to &quot;{1}&quot;.  {2}.
        /// </summary>
        internal static string Extract_ErrorCouldNotExtractFile {
            get {
                return ResourceManager.GetString("Extract.ErrorCouldNotExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3935: Failed to extract file &quot;{0}&quot; because destination file &quot;{1}&quot; is read-only and could not be made writable.  {2}.
        /// </summary>
        internal static string Extract_ErrorCouldNotMakeFileWriteable {
            get {
                return ResourceManager.GetString("Extract.ErrorCouldNotMakeFileWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3933: Failed to open zip file &quot;{0}&quot;.  {1}.
        /// </summary>
        internal static string Extract_ErrorCouldNotOpenFile {
            get {
                return ResourceManager.GetString("Extract.ErrorCouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3934: Failed to open extract file &quot;{0}&quot; to &quot;{1}&quot; because it is outside the destination directory..
        /// </summary>
        internal static string Extract_ErrorExtractingResultsInFilesOutsideDestination {
            get {
                return ResourceManager.GetString("Extract.ErrorExtractingResultsInFilesOutsideDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3932: Failed to extract file &quot;{0}&quot; because the file does not exist or is inaccessible..
        /// </summary>
        internal static string Extract_ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("Extract.ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3937: Failed to parse pattern &quot;{0}&quot; because it contains an invalid path character..
        /// </summary>
        internal static string Extract_ErrorParsingPatternInvalidPath {
            get {
                return ResourceManager.GetString("Extract.ErrorParsingPatternInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3938: Failed to parse pattern &quot;{0}&quot; because it contains a property reference which isn&apos;t supported..
        /// </summary>
        internal static string Extract_ErrorParsingPatternPropertyReferences {
            get {
                return ResourceManager.GetString("Extract.ErrorParsingPatternPropertyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string Extract_FileComment {
            get {
                return ResourceManager.GetString("Extract.FileComment", resourceCulture);
            }
        }
    }
}
